# DataSource Config
spring:
  datasource:
    # driver-class-name: org.h2.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#    schema: classpath:db/schema-h2.sql
#    data: classpath:db/data-h2.sql
#    url: jdbc:h2:tcp://localhost/~/mp_db
    url: jdbc:p6spy:h2:tcp://localhost/~/mp_db
    username: sa
    password: sa
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delete  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

logging:
  level:
    root: warn
    com.mp.second.mappers: trace
  pattern:
    console: '%p%m%n'

